[package]
name = "moly-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
makepad-widgets.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
