[package]
name = "moly-models"
version.workspace = true
edition.workspace = true

[dependencies]
makepad-widgets.workspace = true
moly-data.workspace = true
moly-widgets.workspace = true
log.workspace = true
